#!/usr/bin/env bash

##### CHECK ROOT #####
if [[ $(id -u) -eq 0 ]] ; then
    echo "Перезапустите $0 от обычного пользователя!"
    exit 1
fi

##### DEFAULT VARIABLES #####
SCRIPT_NAME="$(basename "$0")"
if [[ "$(realpath "$0")" == "/usr/bin/$SCRIPT_NAME" ]] ; then
    USER_WORK_PATH="$HOME/.local/share/$SCRIPT_NAME"
    # чуть позже определимся с PYTHON_WORK_PATH, в зависимости от варианта обновления PP
    PYTHON_WORK_PATH=
else
    # для теста создаем и используем каталог test-portproton для исключения взаимодействия с текущей версией
    USER_WORK_PATH="$HOME/test-$SCRIPT_NAME"
    # используем всё из репозитория
    PYTHON_WORK_PATH="$(dirname "$(realpath "$0")")"
fi
export USER_WORK_PATH PYTHON_WORK_PATH

"$PYTHON_WORK_PATH/$SCRIPT_NAME.py" "$@"
